# Generated by Django 5.2.1 on 2025-05-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Explorer", "Explorer"),
                            ("Contributor", "Contributor"),
                            ("Innovator", "Innovator"),
                            ("Visionary", "Visionary"),
                        ],
                        default="Explorer",
                        max_length=12,
                    ),
                ),
                ("joined", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Showcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body_md", models.TextField()),
                ("link", models.URLField(blank=True)),
                ("screenshot", models.ImageField(blank=True, upload_to="screens/")),
                ("approved", models.BooleanField(default=False)),
                ("coins_award", models.PositiveIntegerField(default=0)),
                ("admin_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcases",
                        to="clac.profile",
                    ),
                ),
            ],
        ),
    ]
